### ISSUE TITLE
Full screen applications cause nTaskbar to vanish.

### ISSUE THREAD

**Issue by AnrDaemon** [alur/nModules#12]
[Reported by NilOmniscient, Mar 25, 2014](https://code.google.com/p/n-modules/issues/detail?&id=12)
#### What steps will reproduce the problem?
1. Run x86 Litestep and n-modules on Windows 7 x86_64
2. Set up an nTaskbar
3. Run a full screen application and alt-tab out.

#### What is the expected output? What do you see instead?
Expected output is standard desktop should show up.

Actual output is everything sans nTaskbar.
Sometimes the taskbar will come back with a mouseover, and sometimes a Litestep recycle is required.

#### What version of the product are you using? On what operating system?
nTaskbar 0.6 x86 (32 bit)  and Windows 7 Ultimate x86_64 (64bit)

#### Please provide any additional information below.
Specific application, World of Warcraft. 
Don't run much other than games in full screen. Web browsers, and flash players do not seem to cause the issue either.

**Comment by alur** [comment]
I believe this might be fixed now. Please reopen if you see it again.
