### ISSUE TITLE
nTask: move mouse cursor to a newly activated icon

### ISSUE THREAD

**Issue by AnrDaemon** [alur/nModules#22]
I'm using the so-called "Follow mouse" mode, where applications are activated (receive focus) as the mouse cursor passing over them.
It's nice, when you can reach application with mouse, however, sometimes I find myself in need to use taskbar. But when I click a button on nTask, window is activated, while cursor stays on the bar, and when I try to move it to a newly activated window, sometimes it fall behind other vindows.
I did not find the pattern in that "fall through cracks" behavior, but I think it can be amended, if cursor will move to the activated window upon activation. (Alt+Tab already do that, when "follow mouse" is active.)

**Comment by AnrDaemon** [comment]
The fix appears partial. Elevated windows do not receive focus. Tested on console and GUI window.
Is this something that can be fixed?

**Comment by alur** [comment]
This should be fixed in the rewrite.
