### ISSUE TITLE
nPopup alpha issue

### ISSUE THREAD

**Issue by sryo** [alur/nModules#28]
Steps to reproduce:
nPopupColor #0000
nPopupItemColor transparent
nPopupItemFontColor #000

Expected:
black text over a transparent backgrond. nPopupItemFontColor #fff works.

**Comment by AnrDaemon** [comment]
MY> Steps to reproduce:
MY> nPopupColor #0000
MY> nPopupItemColor transparent
MY> nPopupItemFontColor #000
MY> Expected:
MY> black text over a transparent backgrond. nPopupItemFontColor #fff works.

Have you tried full 32-bit color specifications?

**Comment by sepen77** [comment]
Upon further investigation, it would seem that the transparencies on nPopupItemFontColor affects the transparency of the text just as nPopupItemColor does. However the transparency on nPopupItemFontColor if changed to 0, causes the text's transparency to vary based on its brightness: MY> black text over a transparent backgrond. nPopupItemFontColor #fff works.
It acts like a multiply... for what reason?

**Comment by alur** [comment]
It's some issue with TextAntiAliasMode. Setting it to GrayScale fixes it.

**Comment by alur** [comment]
The quote here seems relevant: http://en.wikipedia.org/wiki/ClearType#ClearType_in_DirectWrite
I think I'll switch the default mode to GrayScale for the 1.0 release.
